name: Rails CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          bundler: 2.6.3

      - name: Clear Bootsnap cache
        run: |
          rm -rf tmp/cache/bootsnap-load-path-cache
          rm -rf tmp/cache/bootsnap-compile-cache
          echo "Bootsnap cache cleared."

      - name: Install Ruby dependencies 
        run: bundle install --jobs 4 --retry 3 --with test

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install JavaScript dependencies
        run: yarn install --frozen-lockfile

      - name: Set up database
        run: |
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:migrate RAILS_ENV=test

      - name: Run tests (RSpec)
        run: /home/runner/work/PetTrack/PetTrack/vendor/bundle/ruby/3.1.0/bin/rspec 
      - name: Precompile assets
        run: |
          RAILS_ENV=production bundle exec rails assets:precompile
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}


      - name: Show build success message
        run: echo "Build, Test, and Asset Precompilation completed successfully!"